version: '2'
services:
  db:
    image: "postgres:13.3"
    restart: always
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - /root/data/library/db_13_3:/var/lib/postgresql/data
    shm_size: '2gb'

  web:
    build: .
    depends_on:
      - db
    links:
      - db
    restart: always
    volumes:
      - /root/data/library/books:/app/public/books/image
    ports:
      - '127.0.0.1:8200:3000'
    env_file:
      - .env
