// Code generated by sqlc. DO NOT EDIT.

package main

import (
	"database/sql"
	"time"
)

type ArInternalMetadatum struct {
	Key       string
	Value     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Book struct {
	ID            int64
	Title         string
	Author        string
	Image         sql.NullString
	Isbn          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ShelfID       sql.NullInt32
	UserID        int64
	GoogleBooksID sql.NullString
	Subtitle      string
	Description   string
	PageCount     int32
	Publisher     string
}

type Highlight struct {
	ID        int64
	BookID    int64
	Page      int32
	Content   string
	Image     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SchemaMigration struct {
	Version string
}

type Shelf struct {
	ID        int64
	Name      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int64
	Position  sql.NullInt32
}

type User struct {
	ID                 int64
	Name               sql.NullString
	Email              sql.NullString
	Image              sql.NullString
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Slug               string
	Description        sql.NullString
	Facebook           sql.NullString
	Twitter            sql.NullString
	Linkedin           sql.NullString
	Instagram          sql.NullString
	Phone              sql.NullString
	Whatsapp           sql.NullString
	Telegram           sql.NullString
	AmazonAssociatesID sql.NullString
}
